runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /tasks/.*
  script: hn-archive.cron_app
  login: admin
- url: /.*
  script: hn-archive.app
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

builtins:
- deferred: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

